import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav-bar";
import NavBottom from "@/components/nav-bottom";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased text-slate-900 bg-white min-h-screen flex flex-col">

        {/* Sticky Header */}
        <header className="sticky top-0 z-50 bg-white border-b border-slate-200 shrink-0">
          <NavBar />
        </header>

        {/* Use pt-[80px - 1], the size of the NavBar header component, so header does not cover content*/}
        <main className="flex-1 flex flex-col min-h-0 pt-[79px]">
          {children}
        </main>
        
        {/* Global Footer */}
        <footer className="w-full shrink-0">
          <NavBottom />
        </footer>
      </body>
    </html>
  );
}