import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased text-slate-900 bg-white">
        {/* Header imported from components folder*/}

        <header className="relative z-50">
          <Header />
        </header>

        <main className="grow">
          {children}
        </main>
        
        {/* Footer imported from components folder */}
        <footer className="relative z-50">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
